
services:
  - type: cron
    name: mcmenamins-room-checker
    schedule: "*/30 * * * *"
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      playwright install chromium
      python main.py
